
useful_names <- c(
  "ID",
  "text",
  "Verified",
  "Retweets",
  "Likes",
  "Quotes",
  "Number of Followers",
  "Number of Accounts Following",
  "Word Count",
  "Analytic Thinking",
  "Clout Language",
  "Authentic Language",
  "Words Longer than 7 Characters",
  "Pronouns for Others (They)",
  "Pronouns for Self (I, Me)",
  "Numeric Content",
  "Affiliation Language",
  "Achievement Language",
  "Power Language",
  "Cognition",
  "All or Nothing Thinking",
  "Cognitive Processing",
  "Insight",
  "Causal Langauge",
  "Discrepencies",
  "Tentativeness",
  "Certitude",
  "Positive Tone",
  "Negative Tone",
  "Anxiousness",
  "Anger",
  "Sadness",
  "Profanity",
  "Social Behavior",
  "Prosociality",
  "Politeness",
  "Conflict",
  "Moralizing",
  "Politics",
  "Curiosity",
  "Influencer",
  "Spread"
)


